### ISSUE TITLE
since go-mcs-sdk is a module, go get go-mcs-sdk is not available

### ISSUE THREAD

**Issue by sonic-chain** [filswan/go-mcs-sdk#22]
module should be declared as github.com/filswan/go-mcs-sdk.

**Comment by PlutoNbai** [comment]
Dora has solve this problem
let us know if you guys still have questions :)

**Comment by sonic-chain** [comment]
Run `go get go-mcs-sdk` prompts the following error: 
go: malformed module path "go-mcs-sdk": missing dot in first path element

**Comment by sonic-chain** [comment]
It has been fixed in the `dev` branch
